### ISSUE TITLE
Build an interface for an order creation service

### ISSUE THREAD

**Issue by billhance** [kole-imports/dropship-api-client#13]
The interface should allow the client to do the following:
- Retrieve batch of orders with support for pagination.
- Retrieve an order by an ID number.
- Create a new order 

In addition there should be methods to return results in multiple formats (object and array at least).

**Comment by messified** [comment]
Starting this now, created new branch issue-13

**Comment by messified** [comment]
Probably should have issued a PR sooner but time is of the essence.
