### ISSUE TITLE
Please fix composer.json

### ISSUE THREAD

**Issue by afstanton** [kole-imports/dropship-api-client#22]
Currently this library cannot be installed via Composer. It needs a "name" entry, and possibly more.

**Comment by afstanton** [comment]
For reference, I've branched this and added these lines to my branch:

```
"name": "catharticbliss/dropship-api-client",
"description": "A library to access Kole Imports API.",
"license": "GPL-3.0",
```

Obviously, you'd probably want to change it from "catharticbliss" to something like "Kole-Imports".

Thanks.

**Comment by messified** [comment]
Will do, thanks.
